name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  workflow_dispatch:  # Allow manual triggers from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify Environment Variables
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        run: |
          echo "🔍 Verifying build environment variables..."

          if [ -z "$VITE_GOOGLE_CLIENT_ID" ]; then
            echo "❌ ERROR: VITE_GOOGLE_CLIENT_ID is not set!"
            echo "Please add VITE_GOOGLE_CLIENT_ID to GitHub Secrets:"
            echo "https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          else
            # Show first 20 chars for verification (don't expose full secret)
            CLIENT_ID_PREFIX="${VITE_GOOGLE_CLIENT_ID:0:20}"
            echo "✅ VITE_GOOGLE_CLIENT_ID is set: ${CLIENT_ID_PREFIX}..."
          fi

          echo ""
          echo "📋 Required Secrets Checklist:"
          echo "  ✅ VITE_GOOGLE_CLIENT_ID - Configured"
          echo "  $([ -n '${{ secrets.CLOUDFLARE_API_TOKEN }}' ] && echo '✅' || echo '❌') CLOUDFLARE_API_TOKEN"
          echo "  $([ -n '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}' ] && echo '✅' || echo '❌') CLOUDFLARE_ACCOUNT_ID"

      - name: Build application
        env:
          # Frontend environment variables (embedded at build time)
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        run: bun run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy

      - name: Deployment Summary
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🌐 Production URL: https://v1-kido-go-game-90976a1a-44ff-4a66-aa8b-a67ff329f54a.farofitus.workers.dev"
