name: Deploy Preview

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy PR Preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify Environment Variables
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        run: |
          echo "🔍 Verifying build environment variables..."

          if [ -z "$VITE_GOOGLE_CLIENT_ID" ]; then
            echo "⚠️ WARNING: VITE_GOOGLE_CLIENT_ID is not set!"
            echo "Google OAuth will use fallback Client ID in preview."
            echo "To fix, add VITE_GOOGLE_CLIENT_ID to GitHub Secrets:"
            echo "https://github.com/${{ github.repository }}/settings/secrets/actions"
          else
            # Show first 20 chars for verification (don't expose full secret)
            CLIENT_ID_PREFIX="${VITE_GOOGLE_CLIENT_ID:0:20}"
            echo "✅ VITE_GOOGLE_CLIENT_ID is set: ${CLIENT_ID_PREFIX}..."
          fi

      - name: Build application
        env:
          # Use same Google Client ID for preview (or create a separate dev one)
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
        run: bun run build

      - name: Deploy Preview to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview
        id: deploy

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment successful!\n\n**Preview URL:** Check the deployment logs above for the preview URL.\n\n_Note: OAuth may not work on preview deployments unless you add the preview URL to Google Cloud Console authorized origins._`
            })
